In [1]:
import numpy as np

In [4]:
b=np.arange(3,16,2)

In [5]:
for i in b.flat:
    print(i)

3
5
7
9
11
13
15


In [6]:
np.argmax(b)

6

In [7]:
print(np.argmax(b),np.max(b))

6 15


In [8]:
np.where(b!=0)

(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)

In [9]:
print (np.where(b!=0))
    

(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)


In [10]:
test=np.array(range(30))

In [12]:
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
test.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [15]:
test.reshape(5,6,order="F")

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [17]:
print(np.where(test%10==1,"Y","N"))

['N' 'Y' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'Y' 'N' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'N' 'Y' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N']


In [18]:
print(np.where(test.reshape(5,6)%10==1,"Y","N"))

[['N' 'Y' 'N' 'N' 'N' 'N']
 ['N' 'N' 'N' 'N' 'N' 'Y']
 ['N' 'N' 'N' 'N' 'N' 'N']
 ['N' 'N' 'N' 'Y' 'N' 'N']
 ['N' 'N' 'N' 'N' 'N' 'N']]


In [19]:
np.exp(1)

2.718281828459045

In [20]:
np.exp(2)

7.38905609893065

In [21]:
np.exp(0)

1.0

In [22]:
np.exp(3)

20.085536923187668

In [23]:
#-----作業-----

In [24]:
a=np.log10(20000/20)
answer=a*20

In [25]:
answer

60.0

In [37]:
G30=10**(30/20)*20

In [36]:
G50=10**(50/20)*20

In [30]:
answer2=G30/G50

In [38]:
print(answer2)
print(G30)
print(G50)

0.09999999999999999
632.4555320336758
6324.555320336759
