In [2]:
#array1 = np.array([[10, 8], [3, 5]])
#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
#運用上列array計算特徵值、特徵向量?
#運用上列array計算SVD?

In [3]:
import numpy as np

In [9]:
array1=np.array([[10,8],[3,5]])
array1_inverse=np.linalg.inv(array1)

In [10]:
array1@array1_inverse

array([[1., 0.],
       [0., 1.]])

In [15]:
w,v=np.linalg.eig(array1)
print("eigenvalue",w)
print("eigenvactor",v)

eigenvalue [13.  2.]
eigenvactor [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [11]:
u,s,vh=np.linalg.svd(array1)

In [12]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [13]:
s

array([13.94721714,  1.86417116])

In [14]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])