In [25]:
import numpy as np

b=np.arange(3,6,1)

In [26]:
b

array([3, 4, 5])

In [27]:
for i in b.flat:
    print (i)

3
4
5


In [28]:
print(np.amax(b),np.amin(b))

5 3


In [29]:
print(np.max(b),np.min(b))

5 3


In [30]:
np.argmax(b) #找出來的是index 

2

In [31]:
np.nonzero(b) #nonzero 等同於 np.where(array != 0) 的語法，同樣的也是回傳符合非 0 條件的元素索引值。

(array([0, 1, 2], dtype=int64),)

In [45]:
np.where(b!=0)

(array([0, 1, 2], dtype=int64),)

In [47]:
np.random.seed(3)
a=np.random.randint(0,20,20)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 12,  7, 14, 17,  2,  2,
        1, 19,  5])

In [35]:
#------------作業區-------------------------作業區------------------作業區----------------------

In [36]:
array1=np.array(range(30))

In [37]:
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [43]:
temp=array1.reshape(5,6)
print(temp)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [41]:
np.where(temp%10==1)

(array([0, 1, 3], dtype=int64), array([1, 5, 3], dtype=int64))

In [44]:
np.where(temp%10==1,"Y","N")

array([['N', 'Y', 'N', 'N', 'N', 'N'],
       ['N', 'N', 'N', 'N', 'N', 'Y'],
       ['N', 'N', 'N', 'N', 'N', 'N'],
       ['N', 'N', 'N', 'Y', 'N', 'N'],
       ['N', 'N', 'N', 'N', 'N', 'N']], dtype='<U1')